language: "python"

python: 
  - "3.7"

env:
  - DJANGO=2.2

install:
  - pip install -r requirements.txt
  - pip install importlib-metadata
  - pip install black
  - pip install flake8
  - pip install coverage
  - pip install coveralls

script:
  - python manage.py test
  - python -m black . --check .
  - black --check .
  - flake8 .
  - coverage run --source=polls manage.py test
  - coverage report -m
  
after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $key_id
  secret_access_key: $access_key
  region: "us-west-2"
  app: "django-tutorial-Assignment-2"
  env: "django-env-assignment-2"
  bucket_name: "elasticbeanstalk-us-west-2-702625943207"
  on:
    branch: main